/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/cawi/2025/kerti_bali': RouteRecordInfo<'/cawi/2025/kerti_bali', '/cawi/2025/kerti_bali', Record<never, never>, Record<never, never>>,
    '/data': RouteRecordInfo<'/data', '/data', Record<never, never>, Record<never, never>>,
    '/form/2025/budaya': RouteRecordInfo<'/form/2025/budaya', '/form/2025/budaya', Record<never, never>, Record<never, never>>,
    '/form/2025/ekonomi_bulan': RouteRecordInfo<'/form/2025/ekonomi_bulan', '/form/2025/ekonomi_bulan', Record<never, never>, Record<never, never>>,
    '/form/2025/wilkerstat': RouteRecordInfo<'/form/2025/wilkerstat', '/form/2025/wilkerstat', Record<never, never>, Record<never, never>>,
    '/kegiatan': RouteRecordInfo<'/kegiatan', '/kegiatan', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/pendataan': RouteRecordInfo<'/pendataan', '/pendataan', Record<never, never>, Record<never, never>>,
    '/success': RouteRecordInfo<'/success', '/success', Record<never, never>, Record<never, never>>,
  }
}
